---
  - name: Configure forwarders
    template:
      src: "templates/named.conf.options.j2"
      dest: "/etc/bind/named.conf.options"
      owner: root
      group: bind
      mode: 0644
    notify:
      - restart bind   
             
  - name: Configure zones
    template:
      src: "templates/named.conf.local.j2"
      dest: "/etc/bind/named.conf.local"
      owner: root
      group: bind
      mode: 0644
    notify:
      - restart bind   

  - name: Loop zones
    template:
      src: "templates/zones.j2"
      dest: "/etc/bind/{{ item.file }}"
      owner: root
      group: bind
      mode: 0644
    with_items: "{{ dns_zones }}"     
    notify:
      - restart bind  
    when: dns_role == "master"


