---
  - name: Configure forwarders
    template:
      src: "templates/named.conf.options.j2"
      dest: "/etc/named/named.conf.options"
      owner: root
      group: named
      mode: 0644
    notify:
      - restart named   
             
  - name: Configure zones
    template:
      src: "templates/named.conf.local.j2"
      dest: "/etc/named/named.conf.local"
      owner: root
      group: named
      mode: 0644
    notify:
      - restart named   

  - name: Zone rpz
    template:
      src: "templates/db.rpz.j2"
      dest: "/etc/named/db.rpz"
      owner: root
      group: named
      mode: 0644 
    notify:
      - restart named 
    when: dns_role == "boss"  

  - name: Loop zones
    template:
      src: "templates/zones.j2"
      dest: "/etc/named/{{ item.file }}"
      owner: root
      group: named
      mode: 0644
    with_items: "{{ dns_zones }}"     
    notify:
      - restart named  
    when: dns_role == "boss"


