---
  - name: Install bind
    yum:
      name={{ packages }}
      state=present
      update_cache=yes
    vars:
      packages:
        - bind 
        - bind-utils

  - name: Update all installed packages
    yum:
      name: '*'
      state: latest
