---
  - name: Install bind
    yum:
      name={{ packages }}
      state=present
      update_cache=yes
    vars:
      packages:
        - bind 
        - bind-utils

  - name: Update all installed packages
    yum:
      name: '*'
      state: latest


  - name: Create cache folder for minion
    file:
      state: directory
      path: /var/cache/named
      owner: root
      group: named
      mode: 0755
    when: dns_role == "minion"


  - name: Allow service through firewall
    firewalld:
      port: 53/udp
      permanent: yes
      state: enabled
      zone: public